from ..strategy import Strategy
import pandas as pd
import pandas_ta as ta
import logging

logger = logging.getLogger(__name__)

class BuilderStrategy(Strategy):
    """
    A generic strategy that executes rules defined in a JSON configuration.
    """
    def init(self):
        # self.params contains the JSON configuration
        # Example config:
        # {
        #   "entry_rules": [...],
        #   "exit_rules": [...],
        #   "sl_pips": 20,
        #   "tp_pips": 40
        # }
        
        self.entry_rules = self.params.get('entry_rules', [])
        self.exit_rules = self.params.get('exit_rules', [])
        self.sl_pips = self.params.get('sl_pips', 0)
        self.tp_pips = self.params.get('tp_pips', 0)
        
        # 1. Identify all required indicators
        self._calculate_indicators()

    def _calculate_indicators(self):
        """
        Parse rules to find all indicators and calculate them using pandas_ta.
        Store results in self.data columns.
        """
        all_rules = self.entry_rules + self.exit_rules
        
        for rule in all_rules:
            # A rule might look like: 
            # { "left": { "type": "indicator", "name": "rsi", "params": {"length": 14} }, ... }
            self._process_operand(rule.get('left'))
            self._process_operand(rule.get('right'))

    def _process_operand(self, operand):
        if not operand or operand.get('type') != 'indicator':
            return

        name = operand.get('name')
        params = operand.get('params', {})
        
        # Construct a unique column name, e.g., "rsi_14"
        # pandas_ta usually appends params to name, but we need to be sure
        # Let's try to invoke pandas_ta dynamically
        
        try:
            # Map common names to pandas_ta functions if needed, or rely on ta.strategy
            # For simplicity, we assume 'name' matches pandas_ta method names (e.g., 'rsi', 'sma', 'ema')
            
            # Check if already calculated
            # We need a consistent naming convention. 
            # Let's use the key generated by pandas_ta or force one.
            
            # Example: ta.rsi(self.data['close'], length=14)
            # We need to pass the correct series (usually close)
            
            # Most indicators use 'close' by default.
            # Some might need 'high', 'low'.
            
            # Dynamic call
            if hasattr(ta, name):
                func = getattr(ta, name)
                
                # Prepare arguments
                # Most ta functions take a Series as first arg (close)
                # Some take open, high, low, close (DataFrame)
                
                # Heuristic: try passing 'close' series first
                # If that fails, pass DataFrame? 
                # pandas_ta is DataFrame extension mostly.
                
                # Better approach: Use the DataFrame extension method directly if possible
                # self.data.ta.rsi(length=14, append=True)
                
                # Construct kwargs
                kwargs = {k: v for k, v in params.items()}
                kwargs['append'] = True # Append to self.data
                
                # Call pandas_ta extension
                # self.data.ta.strategy(...) is for bulk.
                # self.data.ta.rsi(...)
                
                # We can use the 'ta' accessor
                if hasattr(self.data.ta, name):
                    method = getattr(self.data.ta, name)
                    method(**kwargs)
                else:
                    logger.warning(f"Indicator {name} not found in pandas_ta")
                    
        except Exception as e:
            logger.error(f"Failed to calculate indicator {name}: {e}")

    def next(self, i: int, record: dict):
        if i < 1: return # Need at least previous candle for some logic
        
        # Check Exit Rules first
        if self.position:
            if self._evaluate_rules(self.exit_rules, i):
                self.close()
                return

        # Check Entry Rules
        if not self.position:
            if self._evaluate_rules(self.entry_rules, i):
                # Calculate SL/TP prices
                sl_price = None
                tp_price = None
                
                current_price = record['close']
                point = 0.01 if 'JPY' in self.params.get('symbol', '') else 0.0001 # Rough estimation, should come from symbol info
                # Actually, we don't have symbol info here easily unless passed in params.
                # Let's assume standard forex for now or use percentage?
                # For now, simple pips if provided.
                
                # We need to know direction. 
                # The generic builder usually implies a direction based on the rule?
                # Or does the rule specify "Buy if..."?
                # Let's assume Entry Rules = BUY condition.
                # If we want SELL, we might need separate "sell_entry_rules".
                # For MVP, let's assume Entry Rules -> BUY.
                
                # Wait, usually strategies have Buy and Sell logic.
                # The JSON should probably separate them: "buy_rules", "sell_rules".
                # My plan said "Entry Rules" (implied generic).
                # Let's update to support "action" in the rule or top level.
                
                # For MVP: Entry Rules -> BUY.
                
                if self.sl_pips > 0:
                    sl_price = current_price - (self.sl_pips * point)
                if self.tp_pips > 0:
                    tp_price = current_price + (self.tp_pips * point)
                    
                self.buy(sl=sl_price, tp=tp_price)

    def _evaluate_rules(self, rules, i):
        if not rules:
            return False
            
        # AND logic: All rules must be true
        for rule in rules:
            if not self._evaluate_condition(rule, i):
                return False
        return True

    def _evaluate_condition(self, rule, i):
        # rule: { "left": ..., "operator": ">", "right": ... }
        
        left_val = self._get_value(rule.get('left'), i)
        right_val = self._get_value(rule.get('right'), i)
        
        if left_val is None or right_val is None:
            return False
            
        op = rule.get('operator')
        
        if op == '>': return left_val > right_val
        if op == '<': return left_val < right_val
        if op == '>=': return left_val >= right_val
        if op == '<=': return left_val <= right_val
        if op == '==': return left_val == right_val
        
        # Crossover logic requires previous values
        if op == 'CROSS_OVER':
            prev_left = self._get_value(rule.get('left'), i-1)
            prev_right = self._get_value(rule.get('right'), i-1)
            if prev_left is None or prev_right is None: return False
            return prev_left <= prev_right and left_val > right_val
            
        if op == 'CROSS_UNDER':
            prev_left = self._get_value(rule.get('left'), i-1)
            prev_right = self._get_value(rule.get('right'), i-1)
            if prev_left is None or prev_right is None: return False
            return prev_left >= prev_right and left_val < right_val
            
        return False

    def _get_value(self, operand, i):
        if not operand: return None
        
        op_type = operand.get('type')
        
        if op_type == 'value':
            return float(operand.get('value'))
            
        if op_type == 'indicator':
            name = operand.get('name')
            # We need to find the column name generated by pandas_ta
            # pandas_ta names columns like "RSI_14"
            # We can try to guess or search columns
            
            # Exact match attempt (if we knew the exact name)
            # But pandas_ta naming is complex.
            
            # Search for column starting with name (case insensitive)
            # and matching params?
            
            # Simplification: The _calculate_indicators step should have logged or stored the column map.
            # But pandas_ta appends to self.data.
            # Let's look at self.data.columns
            
            # Heuristic: Find column that looks like the indicator
            # e.g. name="rsi", params={"length": 14} -> "RSI_14"
            
            # Let's try to reconstruct the name pandas_ta would use.
            # Usually: NAME_params
            
            # For now, let's just search for the last added column that starts with the name?
            # No, that's risky if multiple RSIs.
            
            # Better: In _calculate_indicators, we can capture the new columns.
            # But pandas_ta modifies in place.
            
            # Let's iterate columns and find best match.
            target_col = None
            
            # Expected format: RSI_14, SMA_20, etc.
            # Convert name to upper
            base_name = name.upper()
            
            # If params has 'length', append it
            length = operand.get('params', {}).get('length')
            if length:
                expected = f"{base_name}_{length}"
                if expected in self.data.columns:
                    target_col = expected
            
            if not target_col:
                # Fallback: exact match of base name (some indicators don't append)
                if base_name in self.data.columns:
                    target_col = base_name
            
            if target_col:
                return self.data[target_col].iloc[i]
                
            # If still not found, maybe it's a standard column like 'close'
            if name.lower() in ['open', 'high', 'low', 'close', 'volume']:
                return self.data[name.lower()].iloc[i]
                
        return None

    @classmethod
    def get_params_schema(cls) -> list:
        # This strategy is dynamic, so it doesn't have fixed params schema for the UI form generator.
        # The UI will be a custom builder.
        return []
